### PR TITLE
Add GH Actions to build on PR and cron

### PR DESCRIPTION
**Pull request by zmichaels11**
Adds in GH Actions CI to repository.
Runs build and test for `macOS-latest` and `ubuntu-18.04` on PR, push to master, and hourly cron.

### CODE REVIEW

**Comment by zmichaels11** [comment]
Action ran in personal fork: https://github.com/zmichaels11/rosbag2_bag_v2/pull/1
I think the macOS build failed due to upstream Catalina issues

These actions will run here once merged in.

**Comment by Karsten1987** [comment]
That's pretty awesome.

The action for ubuntu came back successfully, however when looking at the console output, the build seems to return non-successfully. Also, the actual package didn't build due to a lack of ROS1.
```
-- Override CMake install command with custom implementation using symlinks instead of copying resources
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'roscpp'
--   No package 'roscpp' found
CMake Warning at CMakeLists.txt:30 (message):
  Failed to find ROS 1 roscpp, skipping...


-- Configuring done
-- Generating done
-- Build files have been written to: /home/runner/work/rosbag2_bag_v2/rosbag2_bag_v2/ros2_ws/build/rosbag2_bag_v2_plugins
```
Can we validate the actual return value of `colcon` to see whether errors/warnings occured during the build?

How do you think this package can run on OSX? Is there a way to install ROS1 within the same action?

**Comment by zmichaels11** [comment]
This is using https://github.com/ros-tooling/action-ros2-ci
I'll open up an issue over there, I think it just doesn't support ros1bridge properly.

**Comment by zmichaels11** [comment]
Opened issue on https://github.com/ros-tooling/setup-ros2.

Required fixes for this PR:
- [x] Issue https://github.com/ros-tooling/setup-ros2/issues/21 (Support ROS1)
- [x] Issue https://github.com/ros-tooling/setup-ros2/issues/20 (Support ros1_bridge)

**Comment by zmichaels11** [comment]
This PR requires rework since it depends on feature requests to `action-ros2-ci`.
I'm closing this PR and adding the work required to the AWS backlog.

**Pull request closed without merging**
