### PR TITLE
Add GitHub Actions for linting

### PR DESCRIPTION
**Pull request by zmichaels11**
### Changes
* Add ROS2 GitHub Actions linters (ament_copyright, ament_xmllint, ament_lint_cpp) to project.
* Similar work was done to `rosbag2` here: https://github.com/ros2/rosbag2/pull/227

### Testing
* Results of these changes were tested on this fork: https://github.com/zmichaels11/rosbag2_bag_v2/pull/2

Signed-off-by: Zachary Michaels <zmichaels11@gmail.com>

### CODE REVIEW

**Comment by piraka9011** [comment]
Is there a way we can fix the CMakeLists.txt warning? Maybe by using an `AUTHOR_WARNING` instead?

**Comment by zmichaels11** [comment]
> Is there a way we can fix the CMakeLists.txt warning? Maybe by using an `AUTHOR_WARNING` instead?

I think that should be addressed in a different PR since those warnings are picked up by Jenkins and aren't influencing the added linters

**Comment by zmichaels11** [comment]
@Karsten1987 can you take a look at this?

**Comment by prajakta-gokhale** [comment]
@Karsten1987 this is awaiting your review.

**Comment by Karsten1987** [comment]
Taking the explanation of @thomas-moulard from [here](https://github.com/ros2/rosbag2/pull/227#issuecomment-564331044) I am not sure how to interpret this PR as I only see the PR jobs and DCO on this. What exactly should I see here as checks?

**Comment by piraka9011** [comment]
> I am not sure how to interpret this PR as I only see the PR jobs and DCO on this. What exactly should I see here as checks?

It looks like because this is coming from a fork, the checks are not appearing on this PR. I've seen this happen before in other PRs ([example](https://github.com/aws/aws-dynamodb-encryption-python/pull/134)).

Maybe try this out with a branch local to the repo? @zmichaels11

**Comment by zmichaels11** [comment]
I have the same PR merging into a local branch [here](https://github.com/zmichaels11/rosbag2_bag_v2/pull/2) that runs the linters.
They aren't running on this PR because the PR is coming from a fork.

**Comment by Karsten1987** [comment]
@zmichaels11 can you open a PR from a local branch to see if that works? Also, how is this supposed to work in the future if non-members to this org unit want to open PRs? Then I would have to run the CI on these PRs manually again because the action wouldn't work?

**Comment by zmichaels11** [comment]
@Karsten1987 It doesn't look like I can open a local branch in this repo.
I think the linters would automatically run for forks once enabled on this repo. 

I'll ask @thomas-moulard how he set it up for Rosbag2, since all of the PRs we're submitting to Rosbag2 are running the linters and are coming from a fork.

**Comment by Karsten1987** [comment]
@zmichaels11 you can now push to this repo.

**Comment by zmichaels11** [comment]
Closing in favor of local branch: https://github.com/ros2/rosbag2_bag_v2/pull/15

**Pull request closed without merging**
